# Generated by Django 5.2.3 on 2025-10-29 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_subscription_stripe_subscription_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('free', 'Free'), ('premium', 'Premium'), ('canceled', 'Canceled')], default='free', max_length=10),
        ),
    ]
