# Generated by Django 5.2.3 on 2025-06-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='published_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
