# Generated by Django 5.2.3 on 2025-06-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping', '0002_alter_news_published_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='badge_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
