# Generated by Django 5.2.3 on 2025-06-18 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping', '0003_alter_news_badge_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
