# Generated by Django 5.2.3 on 2025-09-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping', '0004_news_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='published_datetime',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
