# Generated by Django 5.2.3 on 2025-09-09 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrapping', '0005_alter_news_published_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
