# Generated by Django 5.2.3 on 2025-07-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_alter_advertisementimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='category',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
